In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.9.2'

In [ ]:
dataset = pd.read_csv('/content/online_shoppers_intention.csv')
X = dataset.iloc[:, 0:-3].values
y = dataset.iloc[: , -1].values

In [ ]:
print(X)

[[0 0.0 0 ... 1 1 1]
 [0 0.0 0 ... 2 1 2]
 [0 0.0 0 ... 1 9 3]
 ...
 [0 0.0 0 ... 2 1 13]
 [4 75.0 0 ... 2 3 11]
 [0 0.0 0 ... 2 1 2]]


In [ ]:
print(y)

[False False False ... False False False]


In [45]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder() , [1])],remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

IndexError: ignored

In [ ]:
print(X)

  (0, 0)	1.0
  (0, 3338)	1.0
  (0, 3340)	0.2
  (0, 3341)	0.2
  (0, 3344)	2.0
  (0, 3345)	1.0
  (0, 3346)	1.0
  (0, 3347)	1.0
  (0, 3348)	1.0
  (1, 0)	1.0
  (1, 3338)	2.0
  (1, 3339)	64.0
  (1, 3341)	0.1
  (1, 3344)	2.0
  (1, 3345)	2.0
  (1, 3346)	2.0
  (1, 3347)	1.0
  (1, 3348)	2.0
  (2, 0)	1.0
  (2, 3338)	1.0
  (2, 3340)	0.2
  (2, 3341)	0.2
  (2, 3344)	2.0
  (2, 3345)	4.0
  (2, 3346)	1.0
  :	:
  (12327, 3341)	0.086666667
  (12327, 3344)	7.0
  (12327, 3345)	3.0
  (12327, 3346)	2.0
  (12327, 3347)	1.0
  (12327, 3348)	13.0
  (12328, 761)	1.0
  (12328, 3335)	4.0
  (12328, 3338)	15.0
  (12328, 3339)	346.0
  (12328, 3341)	0.021052632
  (12328, 3344)	7.0
  (12328, 3345)	2.0
  (12328, 3346)	2.0
  (12328, 3347)	3.0
  (12328, 3348)	11.0
  (12329, 0)	1.0
  (12329, 3338)	3.0
  (12329, 3339)	21.25
  (12329, 3341)	0.066666667
  (12329, 3344)	7.0
  (12329, 3345)	3.0
  (12329, 3346)	2.0
  (12329, 3347)	1.0
  (12329, 3348)	2.0


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

TypeError: ignored

In [ ]:
from sklearn.preprocessing import StandardScaler   
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
ann = tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))  

In [ ]:
ann.add(tf.keras.layers.Dense(units=6,activation ='relu'))

NameError: ignored

In [ ]:
ann.add(tf.keras.layers.Dense(units=1,activation ='sigmoid'))  

In [ ]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [ ]:
ann.fit(X_train , y_train , batch_size = 32 , epochs = 10)

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)