# **Name --> Shivam Gupta**
# **Roll No. --> 48**
# **University Roll No. --> 2115500132**
# **Section --> " T "**

In [ ]:
import numpy as np

In [ ]:
# 1. Numpy array creating -->

array = np.array([1,2,3,4,5])                  # 1-D array.
print(array,"\n")

My_list = [1,2,3,4,5,6]
array1 = np.array(My_list)
print(array1,"\n")
print(np.ndim(array),"\n")

array2 = np.array([[1,2,3],[4,5,6]])
print(array2,"\n")
print(np.ndim(array2),"\n")

[1 2 3 4 5] 

[1 2 3 4 5 6] 

1 

[[1 2 3]
 [4 5 6]] 

2 



In [ ]:
# 2. Numpy array indexing -->

print(array[1]+array[3],"\n")              # Sum of elements at index 1 and 3.
print(array2[0,1],"\n")                    # Accessing second element of row 1 in 2-D array.

6 

2 



In [ ]:
# 3. Numpy array slicing -->

print(array[1:5],"\n")               # Slicing elements from index 1 to index 5.

[2 3 4 5] 



In [ ]:
# 4. Numpy array Datatypes -->

print(type(array))

<class 'numpy.ndarray'>


In [ ]:
# 5. Numpy array Copy vs View -->

array3 = np.array([1,2,3,4,5])
z = array3.copy()                 # creating copy of array3.
array3[1] = 19
print(array3,"\n",z,"\n")

array4 = np.array([1,2,3,4,5])
y = array4.view()                 # making view of array4.
array4[1] = 19
print(array4,"\n",y,"\n")

[ 1 19  3  4  5] 
 [1 2 3 4 5] 

[ 1 19  3  4  5] 
 [ 1 19  3  4  5] 



In [ ]:
# 6. Numpy Array Shape -->

array5 = np.array([[1,2,3,4],[5,6,7,8]])       # printing shape of array.
print(array5.shape,"\n")

(2, 4) 



In [ ]:
# 7. Numpy array Reshape -->

array6 = np.array([1,2,3,4,5,6,7,8,9])
newarray6 = array6.reshape(3,3)                      # Reshaping 1-D array to 2-D array.
print(newarray6,"\n")

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [ ]:
# 8. Numpy array Iterating -->

array7 = np.array([1,2,3])                        # printing elements of 1-D array.
for x in array7:
  print(x)
print("\n")

array8 = np.array([[1,2,3],[4,5,6]])              # Printing elements of 2-D array.
for x in array8:
  print(x)
print("\n")
for x in array8:                                  # To print all the scalars of 2-D array.
  for y in x:
    print(y)        
print("\n")

1
2
3


[1 2 3]
[4 5 6]


1
2
3
4
5
6




In [ ]:
# 9. Numpy array Join -->

array9 = np.array([1,2,3,4])                            # Joining 2 1-D arrays.
array10 = np.array([5,6,7,8])
array11= np.concatenate((array9,array10))
print(array11)
print("\n")

[1 2 3 4 5 6 7 8]




In [ ]:
# 10. Numpy array Split -->

array12= np.array([1,2,3,4,5,6,7,8,9])
newarr12 = np.array_split(array12,3)                 #spliting one array into 3 arrays.
print(newarr12[0])
print(newarr12[1])
print(newarr12[2])
print("\n")

[1 2 3]
[4 5 6]
[7 8 9]




In [ ]:
# 11. Numpy Searching arrays -->

array13 = np.array([1,4,2,4,3,4])       # find indexes where element 4 is present.
x = np.where(array13==4)
print(x)
print("\n")

(array([1, 3, 5]),)




In [ ]:
# 12. Numpy Sorting arrays -->

array14 = np.array([1,0,3,2])
print(np.sort(array14))
print("\n")

[0 1 2 3]




In [ ]:
# 13. Numpy filter array -->

array15 = np.array([23,24,25,26])
x = [True,True,False,False]
newarray15 = array15[x]
print(newarray15)
print("\n")

[23 24]


